# Generated by Django 6.0.5 on 2026-05-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('simple', 'Simple'), ('doble', 'Doble'), ('suite', 'Suite'), ('vip', 'VIP'), ('vip_premium', 'VIP Premium'), ('vip_gold', 'VIP Gold'), ('vip_diamond', 'VIP Diamond')], max_length=20),
        ),
    ]
